import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import Navbar from "@/components/Navbar";
import styles from "./layout.module.scss"
import AsideMenu from "@/components/AsideMenu";
import Player from "@/components/Player";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.app}>
          <nav>
            <Navbar />
          </nav>
          <aside>
            <AsideMenu />
          </aside>
          <main>
            {children}
          </main>
          <footer>
            <Player />
          </footer>
        </div>
      </body>
    </html>
  );
}
