'use client'

import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.scss";
import Navbar from "@/components/Navbar";
import styles from "./layout.module.scss"
import AsideMenu from "@/components/AsideMenu";
import Player from "@/components/Player";
import { createContext, useState } from "react";

export const PlayerContext = createContext()

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [currentMusic, setCurrentMusic] = useState(null)
  const [isPlaying, setIsPlaying] = useState(false)


  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <PlayerContext.Provider
          value={{
            currentMusic, 
            setCurrentMusic,
            isPlaying,
            setIsPlaying
          }}
        >
          <div className={styles.app}>
            <nav>
              <Navbar />
            </nav>
            <aside>
              <AsideMenu />
            </aside>
            <main>
              {children}
            </main>
            <footer>
              <Player />
            </footer>
          </div>
        </PlayerContext.Provider>

      </body>
    </html>
  );
}
